{{- if .Values.cluster.inline }}
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: inline-2
{{- if eq .Values.cluster.type "physical" }}
plugin: sriov
{{- else }}
plugin: macvlan
{{- end }}
 
args: '[
       {
                {{- if eq .Values.cluster.type "physical" }}
                "if0": "{{ .Values.networkInterfaces.inline2interface.deviceName }}",
                {{- else }}
                "master": "{{ .Values.networkInterfaces.inline2interface.deviceName }}",
                {{- end }}
                "ipam": {
                  "type": "host-local",
                  "subnet": "10.4.0.0/16",
                  "rangeStart": "10.4.0.10",
                  "rangeEnd": "10.4.0.150"
                }
        }
]'
{{- end }}
